name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change if your default branch is 'master'

jobs:
  build-and-deploy:
    name: Build and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # ✅ Proper authentication using google-github-actions/auth
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # ✅ Setup gcloud CLI with the authenticated credentials
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # ✅ Authenticate Docker with Artifact Registry
    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t us-central1-docker.pkg.dev/numeric-advice-463218-r7/gemini-langchain-api-repo/gemini-api .

    - name: Push Docker image
      run: docker push us-central1-docker.pkg.dev/numeric-advice-463218-r7/gemini-langchain-api-repo/gemini-api

    - name: Deploy to Cloud Run
      run: |
       gcloud run deploy gemini-api \
        --image us-central1-docker.pkg.dev/numeric-advice-463218-r7/gemini-langchain-api-repo/gemini-api \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated

